name: flutter_rest_data
description: Easily persist on device REST data from your backend
version: 0.0.1
author: Algonauti <info@algonauti.com>
homepage: https://www.algonauti.com

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  hive_flutter:
    git:
      url: git://github.com/hivedb/hive.git
      path: hive_flutter
  rest_data: ^0.3.2
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
