name: flutter_rest_data
description: Easily persist on device REST data from your backend
version: 0.0.1
homepage: https://www.algonauti.com
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  rest_data: ^0.4.0
  hive_flutter: ^1.1.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
